version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '20:00'
  open-pull-requests-limit: 30
  ignore:
    - dependency-name: 'sass-loader'
      versions:
        - '>12'
